version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  vehicle-service:
    build: .
    container_name: vehicle-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/vehicle_management
      - PORT=3000
    depends_on:
      - mongodb

volumes:
  mongo-data:
